# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: 'Install requirments'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ make python3 python3-dev lua5.1 liblua5.1-dev zip unzip
      - name: 'Clone and build vim'
        run: |
          git clone https://github.com/vim/vim
          cd vim
          mkdir /home/runner/work/vim-debian-build/vim-debian-bin
          ./configure --with-features=huge \
            --enable-multibyte \
            --enable-pythoninterp=yes \
            --with-python-config-dir=$(python-config --configdir) \
            --enable-python3interp=yes \
            --with-python3-config-dir=$(python3-config --configdir) \
            --enable-luainterp=yes \
            --enable-gui=no \
            --enable-cscope \
            --prefix=/home/runner/work/vim-debian-build/vim-debian-bin
          make
          sudo make install
      - name: 'Zip bin'
        run: |
          zip –r vim.zip /home/runner/work/vim-debian-build/vim-debian-bin
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: vim.zip
          path: vim.zip
